# Generated by Django 4.2.2 on 2023-06-27 07:08

import cadastro.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=300, unique=True)),
                ('imagem', models.ImageField(upload_to=cadastro.models.image_path)),
                ('descricao', models.CharField(max_length=300)),
                ('preparacao', models.CharField(blank=True, max_length=10000)),
                ('como_conservar', models.CharField(max_length=1000)),
                ('data_de_fabricacao_produto', models.DateField()),
                ('tempo_para_vencimento_produto', models.PositiveIntegerField()),
                ('data_vencimento_produto', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(default='formate o nome do produto assim: nome_do_produto', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesNutricionais',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cadastro.cadastrodeprodutos')),
                ('carboidratos', models.CharField(max_length=100)),
                ('gorduras', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cadastrodeprodutos',
            name='categorias',
            field=models.ManyToManyField(to='cadastro.categoria'),
        ),
    ]
